
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 121
#define YY_END_OF_BUFFER 122
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[417] =
    {   0,
        0,    0,    0,    0,    0,    0,  122,  112,    2,    1,
        1,   22,  100,  104,   25,   35,  102,   12,   13,   23,
       19,    9,   20,    7,   24,  111,  111,   16,    8,   29,
       15,   30,   40,   14,    5,    6,   36,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   10,   37,   11,   21,  115,  114,  114,
      115,  120,  119,  119,  116,  118,    1,   34,  104,   43,
       38,   49,    0,    0,    0,   41,   17,   44,   18,   45,
      103,  103,    4,    3,   42,  103,  109,  109,  110,  108,
      103,    0,  111,  106,    0,  111,  111,    0,   26,   31,

       33,   32,   27,   50,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   75,  104,  104,  104,  104,  104,
      104,  104,  104,   62,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,   51,   39,  114,  113,  119,  117,  101,
      102,    0,    0,  103,    0,  103,  103,    0,    3,  103,
      103,  103,    0,  109,  109,  109,  110,    0,  110,    0,
      107,    0,  103,  103,    0,  105,  109,  110,  111,   46,
       47,   28,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

       74,  104,  104,  104,   55,  104,  104,   72,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   78,  104,  104,  104,    0,    0,
        0,  103,  103,  103,  103,  103,    0,    0,  103,  103,
      109,  110,  107,  107,    0,  103,  103,  103,    0,    0,
        0,  105,  105,    0,    0,    0,   48,  104,  104,  104,
      104,   53,   65,  104,   57,  104,  104,  104,  104,  104,
       63,   97,  104,  104,  104,  104,  104,  104,  104,  104,
       56,  104,   99,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,   71,  104,  104,   98,   61,  104,

      104,  103,  103,    0,  103,  103,  103,    0,  103,    0,
        0,    0,  103,  103,  105,  104,  104,  104,   68,   79,
       60,  104,  104,  104,  104,   84,   58,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,   54,  104,  104,
       76,  104,  104,   77,  104,  104,   67,  103,  103,    0,
      103,  103,  103,    0,  104,  104,  104,  104,   59,  104,
      104,  104,   96,  104,  104,   89,  104,  104,  104,   81,
       70,   82,  104,   64,  104,   94,  104,  104,  103,  104,
       52,  104,   66,   95,   85,  104,  104,  104,   80,   88,
      104,  104,  104,  104,  104,   83,   69,  104,  104,  104,

      104,  104,  104,   93,  104,  104,   87,   90,  104,   92,
       86,   73,  104,  104,   91,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   22,   22,   22,   23,   23,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   31,   33,   34,   33,
        7,    7,    7,    7,    7,   35,    7,    7,    7,   36,
        7,    7,    7,    7,    7,    7,    7,   37,    7,    7,
       38,   39,   40,   41,   42,    1,   43,   44,   45,   46,

       47,   48,   49,   50,   51,    7,   52,   53,   54,   55,
       56,   57,    7,   58,   59,   60,   61,   62,   63,   64,
       65,   66,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[71] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    1,    1,    1,
        6,    6,    6,    6,    7,    8,    4,    1,    1,    1,
        1,    9,    6,    6,    6,    6,    6,    6,    4,    4,
        4,    4,    7,    4,    4,    4,    8,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[428] =
    {   0,
        0,    0,   68,   70,   72,   76,  816,  931,  931,  931,
      812,  782,  931,    0,  779,   68,   74,  931,  931,  777,
       71,  931,   70,   68,   81,   99,  147,  931,  931,   66,
      776,   73,  931,  931,  931,  931,  775,   58,   47,  101,
       67,   71,   53,  744,   94,  743,  112,   67,  746,  111,
       79,  734,  738,  931,  111,  931,  931,  931,  931,  784,
      768,  931,  931,  781,  931,  177,  931,  931,    0,  931,
      931,  931,  773,  767,  232,  931,  931,  931,  931,  931,
      226,  274,  931,    0,  931,  279,  153,  182,  311,  120,
      931,  242,  931,  757,  188,    0,    0,  247,  745,  931,

      931,  931,  150,  931,  712,  708,  705,  712,  698,  132,
      714,  713,  699,  705,  691,  692,  678,  677,  683,  680,
      677,  674,  671,    0,  673,  139,  673,  667,  663,  671,
      678,  102,  678,  661,  648,  107,  645,  650,  642,  161,
      153,  109,  645,  931,  931,  931,  931,  931,  931,  931,
      931,  319,  327,  931,  263,    0,    0,  341,    0,  346,
      376,  931,  368,  931,    0,    0,    0,  383,    0,  392,
      366,  351,  407,  416,    0,  415,  424,  459,    0,  931,
      931,  668,  633,  645,  638,  645,  640,  639,  639,  625,
      623,  163,  638,  620,  615,  607,  610,  597,  612,  610,

        0,  596,   74,  591,  602,  599,  596,    0,  593,  592,
      581,  582,  588,  563,  565,  561,  566,  567,  553,  561,
      546,  545,  544,  548,    0,  548,  545,  533,  464,  575,
      468,  473,  489,    0,    0,    0,  494,  504,  519,  524,
        0,    0,  529,  931,  208,  931,  554,  570,  539,  184,
      177,  562,  931,  606,  542,  588,  931,  525,  522,  531,
      517,    0,    0,  518,    0,  504,  496,  504,  493,  500,
        0,    0,  496,  503,  481,  473,  485,  472,  486,  470,
        0,  458,    0,  475,  464,  458,  453,  445,  442,  449,
      454,  440,  452,  426,    0,  412,  414,    0,    0,  411,

      423,  612,  617,  647,    0,  652,  657,  687,  692,  267,
      427,  697,  722,  727,    0,  424,  405,  418,    0,    0,
        0,  405,  403,  407,  406,  388,    0,  379,  371,  366,
      372,  370,  367,  347,  355,  336,  323,    0,  332,  316,
        0,  325,  298,  296,  303,  301,    0,  743,  759,  406,
      931,  775,  791,  806,  306,  295,  282,  282,    0,  277,
      270,  276,    0,  274,  275,    0,  270,  268,  254,    0,
        0,    0,  263,    0,  254,    0,  259,  252,  821,  244,
        0,  244,    0,    0,    0,  233,  234,  233,    0,    0,
      228,  200,  200,  189,  196,    0,    0,  180,  183,  189,

      187,  180,  169,    0,  156,  138,    0,    0,  118,    0,
        0,    0,  128,  110,    0,  931,  869,  878,  884,  893,
      902,  907,  101,  909,  913,  917,  921
    } ;

static const flex_int16_t yy_def[428] =
    {   0,
      416,    1,  417,  417,  418,  418,  416,  416,  416,  416,
      416,  416,  416,  419,  416,  416,  420,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  419,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  421,  416,  416,   26,   87,  416,  416,
      416,  416,  416,  422,  416,   27,   27,  416,  416,  416,

      416,  416,  416,  416,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,   82,   82,  416,  421,  416,
      416,  416,  416,  416,   88,   88,   89,  416,   89,  416,
      416,  416,  416,  416,  423,  424,  416,  416,   27,  416,
      416,  416,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  416,  416,
      416,  416,  416,   82,  161,  161,  416,  416,  416,  416,
       88,   89,  416,  416,  416,  416,  416,  416,  416,  425,
      423,  424,  416,  416,  426,  416,  416,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  416,  416,  416,  161,  416,  416,  416,  416,  425,
      427,  416,  416,  416,  252,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  416,  416,  425,
      416,  416,  416,  416,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  416,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,

      419,  419,  419,  419,  419,  419,  419,  419,  419,  419,
      419,  419,  419,  419,  419,    0,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416
    } ;

static const flex_int16_t yy_nxt[1002] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       27,   27,   27,   28,   29,   30,   31,   32,   33,   34,
       14,   14,   14,   14,   14,   14,   14,   35,    8,   36,
       37,   14,   38,   39,   40,   41,   42,   43,   44,   14,
       45,   14,   46,   14,   47,   14,   48,   49,   50,   51,
       14,   52,   53,   14,   14,   14,   54,   55,   56,   57,
       59,   60,   59,   60,   63,   64,   71,   65,   63,   64,
       61,   65,   61,   74,   77,   79,   81,   82,   82,   82,
       82,   99,  100,   83,   72,  119,   80,   78,   84,  102,

      103,  105,  107,  120,  108,  121,  250,   85,  122,  131,
       66,  109,   75,  114,   66,   86,  106,   87,   88,   88,
       88,   89,  115,  116,  132,  117,  277,  133,  140,  278,
       90,   91,   92,   93,  118,   94,  141,  144,  171,  171,
       95,  124,   90,  110,   91,   92,   91,  125,  126,  216,
      111,   93,  211,  112,  128,  415,  113,  212,  129,  226,
      135,  227,   94,   86,  217,   96,   97,   97,   97,   97,
      136,  137,  130,  138,  414,  139,  181,  182,  145,   91,
       92,   93,  149,  413,  416,  412,  149,  164,   98,  416,
      188,  189,   91,   92,   91,  223,  416,  204,  205,   93,

      165,  166,  166,  166,  167,  164,  177,  177,  177,  177,
      178,  221,  254,  224,  411,  149,  416,  225,  222,  254,
      149,  267,  268,  168,  149,  311,  243,  243,  410,   95,
      409,  149,  408,  254,  149,  407,  149,   73,  406,  405,
      254,   73,  404,  403,   81,   82,   82,   82,   82,  245,
      152,  152,  152,  153,  402,  172,  272,  172,  154,  155,
      173,  174,  174,  174,  174,  179,  179,  179,  179,  179,
       73,  154,  155,  154,  401,   73,  231,  400,  231,   73,
      399,  232,  233,  233,  233,  233,   73,  398,   98,   73,
      397,   73,  156,  157,  157,  157,  157,  160,  161,  161,

      161,  161,  254,  396,  395,  394,  154,  155,  311,  393,
      392,  162,  163,  391,  390,  158,  389,  388,  387,  154,
      155,  154,  386,  254,  162,  163,  162,   86,  150,  169,
      167,  167,  167,  167,  385,  384,  150,  229,  229,  229,
      229,  383,  382,   91,   92,  230,  230,  230,  230,  381,
      380,  378,  170,  377,  376,  375,   91,   92,   91,  234,
      234,  234,  234,  234,  160,  161,  161,  161,  161,  173,
      174,  174,  174,  174,  374,  373,  372,  371,  162,  163,
      370,  238,  158,  238,  243,  243,  239,  240,  240,  240,
      240,  162,  163,  162,  235,  236,  236,  236,  236,  369,

      244,  241,  241,  241,  241,  242,  368,  245,  162,  163,
      242,  242,  242,  242,  242,  367,  366,  237,  244,  365,
      364,  162,  163,  162,  168,  173,  174,  174,  174,  174,
      363,  251,  362,  170,  247,  248,  248,  248,  248,  246,
      361,  254,  177,  177,  177,  177,  178,  311,  246,  253,
      254,  360,  246,  359,  246,  358,  255,  249,  164,  357,
      356,  246,  254,  246,  272,   95,  355,  253,  311,  347,
      346,  254,  345,  150,  344,  343,  164,  178,  178,  178,
      178,  178,   73,   73,   73,   73,  232,  233,  233,  233,
      233,  232,  233,  233,  233,  233,  342,  341,  340,  339,

      256,  338,  337,  336,  335,  154,  334,  302,  303,  303,
      303,  303,  305,  305,  305,  305,  305,  333,  154,  332,
      154,  154,  239,  240,  240,  240,  240,  331,  330,  329,
      304,  328,  327,  326,  154,  237,  154,  239,  240,  240,
      240,  240,  306,  307,  307,  307,  307,  243,  243,  298,
      325,  162,  324,  323,  322,  272,  162,  309,  309,  309,
      309,  309,  321,  244,  162,  308,  162,  320,  319,  162,
      245,  162,  247,  248,  248,  248,  248,  318,  251,  317,
      249,  244,  316,  255,  150,  301,  246,  300,  247,  248,
      248,  248,  248,  299,  298,  249,  253,  254,  297,  246,

      296,  246,  246,  255,  295,  294,  178,  178,  178,  178,
      178,  249,  293,  292,  253,  246,  291,  246,  254,  312,
      290,  312,  289,  288,  313,  314,  314,  314,  314,  256,
      302,  303,  303,  303,  303,  302,  303,  303,  303,  303,
      287,  286,  285,  284,  154,  283,  282,  281,  280,  154,
      279,  272,  276,  304,  275,  274,  273,  154,  304,  154,
      272,  271,  154,  270,  154,  348,  348,  348,  348,  348,
      306,  307,  307,  307,  307,  306,  307,  307,  307,  307,
      269,  266,  265,  264,  162,  263,  262,  261,  304,  162,
      260,  259,  258,  308,  257,  228,  220,  162,  308,  162,

      219,  218,  162,  215,  162,  349,  349,  349,  349,  349,
      247,  248,  248,  248,  248,  313,  314,  314,  314,  314,
      214,  213,  210,  209,  246,  208,  207,  206,  308,  203,
      202,  201,  200,  249,  199,  198,  197,  246,  196,  246,
      313,  314,  314,  314,  314,  352,  353,  353,  353,  353,
      195,  194,  193,  192,  351,  191,  190,  187,  186,  351,
      185,  302,  303,  303,  303,  303,  184,  351,  354,  351,
      183,  180,  351,  175,  351,  154,  151,  306,  307,  307,
      307,  307,  150,  148,  304,  147,  146,  143,  154,  142,
      154,  162,  134,  352,  353,  353,  353,  353,  127,  123,

      308,  104,  101,   76,  162,   70,  162,  351,   68,  352,
      353,  353,  353,  353,   67,  416,  354,  416,  416,  416,
      351,  416,  351,  351,  379,  379,  379,  379,  379,  416,
      416,  416,  354,  416,  416,  416,  351,  416,  351,  352,
      353,  353,  353,  353,  416,  416,  416,  354,  416,  416,
      416,  416,  416,  351,  416,  416,  416,  416,  416,  416,
      416,  416,  354,  416,  416,  416,  351,  416,  351,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   69,  416,   69,
       69,   69,   69,   73,  416,  416,   73,   73,   73,   73,

       73,   73,  159,  416,  159,  159,  159,  159,  159,  159,
      159,  176,  176,  252,  252,  252,  252,  252,  310,  416,
      310,  310,  315,  416,  416,  315,  350,  416,  416,  350,
        7,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416
    } ;

static const flex_int16_t yy_chk[1002] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,    5,    5,   16,    5,    6,    6,
        3,    6,    4,   17,   21,   23,   24,   24,   24,   24,
       24,   30,   30,   25,   16,   43,   23,   21,   25,   32,

       32,   38,   39,   43,   39,   43,  423,   25,   43,   48,
        5,   39,   17,   41,    6,   26,   38,   26,   26,   26,
       26,   26,   41,   42,   48,   42,  203,   48,   51,  203,
       26,   26,   26,   26,   42,   26,   51,   55,   90,   90,
       26,   45,   26,   40,   26,   26,   26,   45,   45,  136,
       40,   26,  132,   40,   47,  414,   40,  132,   47,  142,
       50,  142,   26,   27,  136,   27,   27,   27,   27,   27,
       50,   50,   47,   50,  413,   50,  103,  103,   55,   27,
       27,   27,   66,  409,   87,  406,   66,   87,   27,   87,
      110,  110,   27,   27,   27,  141,   87,  126,  126,   27,

       88,   88,   88,   88,   88,   87,   95,   95,   95,   95,
       95,  140,  251,  141,  405,   66,   87,  141,  140,  250,
       66,  192,  192,   88,   66,  250,  245,  245,  403,   95,
      402,   66,  401,  251,   66,  400,   66,   75,  399,  398,
      250,   75,  395,  394,   81,   81,   81,   81,   81,  245,
       75,   75,   75,   75,  393,   92,  392,   92,   81,   81,
       92,   92,   92,   92,   92,   98,   98,   98,   98,   98,
       75,   81,   81,   81,  391,   75,  155,  388,  155,   75,
      387,  155,  155,  155,  155,  155,   75,  386,   98,   75,
      382,   75,   82,   82,   82,   82,   82,   86,   86,   86,

       86,   86,  310,  380,  378,  377,   82,   82,  310,  375,
      373,   86,   86,  369,  368,   82,  367,  365,  364,   82,
       82,   82,  362,  310,   86,   86,   86,   89,  152,   89,
       89,   89,   89,   89,  361,  360,  153,  152,  152,  152,
      152,  358,  357,   89,   89,  153,  153,  153,  153,  356,
      355,  346,   89,  345,  344,  343,   89,   89,   89,  158,
      158,  158,  158,  158,  160,  160,  160,  160,  160,  172,
      172,  172,  172,  172,  342,  340,  339,  337,  160,  160,
      336,  163,  158,  163,  171,  171,  163,  163,  163,  163,
      163,  160,  160,  160,  161,  161,  161,  161,  161,  335,

      171,  168,  168,  168,  168,  168,  334,  171,  161,  161,
      170,  170,  170,  170,  170,  333,  332,  161,  171,  331,
      330,  161,  161,  161,  168,  173,  173,  173,  173,  173,
      329,  176,  328,  170,  174,  174,  174,  174,  174,  173,
      326,  350,  177,  177,  177,  177,  177,  350,  174,  176,
      176,  325,  173,  324,  173,  323,  176,  174,  177,  322,
      318,  174,  350,  174,  317,  177,  316,  176,  311,  301,
      300,  176,  297,  229,  296,  294,  177,  178,  178,  178,
      178,  178,  229,  229,  229,  229,  231,  231,  231,  231,
      231,  232,  232,  232,  232,  232,  293,  292,  291,  290,

      178,  289,  288,  287,  286,  232,  285,  233,  233,  233,
      233,  233,  237,  237,  237,  237,  237,  284,  232,  282,
      232,  233,  238,  238,  238,  238,  238,  280,  279,  278,
      233,  277,  276,  275,  233,  237,  233,  239,  239,  239,
      239,  239,  240,  240,  240,  240,  240,  243,  243,  274,
      273,  239,  270,  269,  268,  267,  240,  249,  249,  249,
      249,  249,  266,  243,  239,  240,  239,  264,  261,  240,
      243,  240,  247,  247,  247,  247,  247,  260,  252,  259,
      249,  243,  258,  255,  230,  228,  247,  227,  248,  248,
      248,  248,  248,  226,  224,  247,  252,  252,  223,  247,

      222,  247,  248,  252,  221,  220,  256,  256,  256,  256,
      256,  248,  219,  218,  252,  248,  217,  248,  252,  254,
      216,  254,  215,  214,  254,  254,  254,  254,  254,  256,
      302,  302,  302,  302,  302,  303,  303,  303,  303,  303,
      213,  212,  211,  210,  302,  209,  207,  206,  205,  303,
      204,  202,  200,  302,  199,  198,  197,  302,  303,  302,
      196,  195,  303,  194,  303,  304,  304,  304,  304,  304,
      306,  306,  306,  306,  306,  307,  307,  307,  307,  307,
      193,  191,  190,  189,  306,  188,  187,  186,  304,  307,
      185,  184,  183,  306,  182,  143,  139,  306,  307,  306,

      138,  137,  307,  135,  307,  308,  308,  308,  308,  308,
      309,  309,  309,  309,  309,  312,  312,  312,  312,  312,
      134,  133,  131,  130,  309,  129,  128,  127,  308,  125,
      123,  122,  121,  309,  120,  119,  118,  309,  117,  309,
      313,  313,  313,  313,  313,  314,  314,  314,  314,  314,
      116,  115,  114,  113,  313,  112,  111,  109,  108,  314,
      107,  348,  348,  348,  348,  348,  106,  313,  314,  313,
      105,   99,  314,   94,  314,  348,   74,  349,  349,  349,
      349,  349,   73,   64,  348,   61,   60,   53,  348,   52,
      348,  349,   49,  352,  352,  352,  352,  352,   46,   44,

      349,   37,   31,   20,  349,   15,  349,  352,   12,  353,
      353,  353,  353,  353,   11,    7,  352,    0,    0,    0,
      352,    0,  352,  353,  354,  354,  354,  354,  354,    0,
        0,    0,  353,    0,    0,    0,  353,    0,  353,  379,
      379,  379,  379,  379,    0,    0,    0,  354,    0,    0,
        0,    0,    0,  379,    0,    0,    0,    0,    0,    0,
        0,    0,  379,    0,    0,    0,  379,    0,  379,  417,
      417,  417,  417,  417,  417,  417,  417,  417,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  419,    0,  419,
      419,  419,  419,  420,    0,    0,  420,  420,  420,  420,

      420,  420,  421,    0,  421,  421,  421,  421,  421,  421,
      421,  422,  422,  424,  424,  424,  424,  424,  425,    0,
      425,  425,  426,    0,    0,  426,  427,    0,    0,  427,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  416,  416,  416,  416,  416,

      416
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 2 "lexer.l"
#include "node.hpp"
#include "y.tab.h"
#include<bits/stdc++.h>
#line 811 "lex.yy.c"

#line 813 "lex.yy.c"

#define INITIAL 0
#define IN_COMMENT 1
#define IN_STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 150 "lexer.l"

#line 1034 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 417 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 931 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 152 "lexer.l"
{yylineno++; }   // removing spaces tabs newlines
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 154 "lexer.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 156 "lexer.l"
;   // removing comments
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 160 "lexer.l"
BEGIN(IN_COMMENT); yymore();
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 165 "lexer.l"
{ 
				           yylval.node_type = new Node("SeparatorLSqBrac", string(yytext));
                                            return SeparatorLSqBrac ;
						}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 169 "lexer.l"
{ 
						yylval.node_type = new Node("SeparatorRSqBrac", string(yytext));
							return SeparatorRSqBrac ;
						}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 173 "lexer.l"
{          yylval.node_type = new Node("SeparatorDot", string(yytext));
							 return SeparatorDot ;
						}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 177 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorSemiCo", string(yytext)); return SeparatorSemiCo ;
						}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 180 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorComma", string(yytext)); return SeparatorComma ;
						}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 183 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorLCuBrac", string(yytext)); return SeparatorLCuBrac ;
						}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 186 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorRCuBrac", string(yytext)); return SeparatorRCuBrac ;
						}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 189 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorLParen", string(yytext)); return SeparatorLParen ;
						}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 192 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorRParen", string(yytext)); return SeparatorRParen ;
						}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 195 "lexer.l"
{ 
							yylval.node_type = new Node("SeparatorAlpha", string(yytext)); return SeparatorAlpha ;
						}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 199 "lexer.l"
{
							yylval.node_type = new Node("OperatorEq", string(yytext)); return OperatorEq ;
						}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 202 "lexer.l"
{
							yylval.node_type = new Node("OperatorColon", string(yytext)); return OperatorColon ;
						}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 205 "lexer.l"
{
							yylval.node_type = new Node("OperatorPlPl", string(yytext)); return OperatorPlPl ;
						}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 208 "lexer.l"
{
							yylval.node_type = new Node("OperatorMiMi", string(yytext)); return OperatorMiMi;
						}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 211 "lexer.l"
{
							yylval.node_type = new Node("OperatorPl", string(yytext)); return OperatorPl;
						}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 214 "lexer.l"
{
							yylval.node_type = new Node("OperatorMi", string(yytext)); return OperatorMi;
						}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 217 "lexer.l"
{
							yylval.node_type = new Node("OperatorTild", string(yytext)); return OperatorTild;
						}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 220 "lexer.l"
{
							yylval.node_type = new Node("OperatorExcl", string(yytext)); return OperatorExcl;
						}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 223 "lexer.l"
{
							yylval.node_type = new Node("OperatorMul", string(yytext)); return OperatorMul;
						}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 226 "lexer.l"
{
							yylval.node_type = new Node("OperatorDiv", string(yytext)); return OperatorDiv;
						}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 229 "lexer.l"
{
							yylval.node_type = new Node("OperatorPerc", string(yytext)); return OperatorPerc;
						}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 232 "lexer.l"
{
							yylval.node_type = new Node("OperatorLele", string(yytext)); return OperatorLeLe;
						}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 235 "lexer.l"
{
							yylval.node_type = new Node("OperatorGrGr", string(yytext)); return OperatorGrGr;
						}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 238 "lexer.l"
{
							yylval.node_type = new Node("OperatorGrGr", string(yytext)); return OperatorGrGrGr;
						}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 241 "lexer.l"
{
							yylval.node_type = new Node("OperatorLe", string(yytext)); return OperatorLe;
						}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 244 "lexer.l"
{
							yylval.node_type = new Node("OperatorGr", string(yytext)); return OperatorGr;
						}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 247 "lexer.l"
{
							yylval.node_type = new Node("OperatorLeEq", string(yytext)); return OperatorLeEq;
						}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 250 "lexer.l"
{
							yylval.node_type = new Node("OperatorGrEq", string(yytext)); return OperatorGrEq;
						}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 253 "lexer.l"
{
							yylval.node_type = new Node("OperatorEqEq", string(yytext)); return OperatorEqEq;
						}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 256 "lexer.l"
{
							yylval.node_type = new Node("OperatorNE", string(yytext)); return OperatorNE;
						}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 259 "lexer.l"
{
							yylval.node_type = new Node("OperatorAmp", string(yytext)); return OperatorAmp;
						}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 263 "lexer.l"
{
							yylval.node_type = new Node("OperatorUp", string(yytext)); return OperatorUp;
						}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 266 "lexer.l"
{
							yylval.node_type = new Node("OperatorVert", string(yytext)); return OperatorVert;
						}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 269 "lexer.l"
{
							yylval.node_type = new Node("OperatorAnd", string(yytext)); return OperatorAnd;
						}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 272 "lexer.l"
{
							yylval.node_type = new Node("OperatorOr", string(yytext)); return OperatorOr;
						}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 275 "lexer.l"
{
							yylval.node_type = new Node("OperatorQm", string(yytext)); return OperatorQm;
						}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 278 "lexer.l"
{
							yylval.node_type = new Node("OperatorAsEq", string(yytext)); return OperatorAsEq;
						}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 281 "lexer.l"
{
							yylval.node_type = new Node("OperatorSlEq", string(yytext)); return OperatorSlEq;
						}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 284 "lexer.l"
{
							yylval.node_type = new Node("OperatorPercEq", string(yytext)); return OperatorPercEq;
						}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 287 "lexer.l"
{
							yylval.node_type = new Node("OperatorPlEq", string(yytext)); return OperatorPlEq;
						}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 290 "lexer.l"
{
							yylval.node_type = new Node("OperatorMiEq", string(yytext)); return OperatorMiEq;
						}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 293 "lexer.l"
{
							yylval.node_type = new Node("OperatorLeLeEq", string(yytext)); return OperatorLeLeEq;
						}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 296 "lexer.l"
{
							yylval.node_type = new Node("OperatorGrGrEq", string(yytext)); return OperatorGrGrEq;
						}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 299 "lexer.l"
{
							yylval.node_type = new Node("OperatorGrGrGrEq", string(yytext)); return OperatorGrGrGrEq;
						}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 302 "lexer.l"
{
							yylval.node_type = new Node("OperatorAmpEq", string(yytext)); return OperatorAmpEq;
						}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 305 "lexer.l"
{
							yylval.node_type = new Node("OperatorUpEq", string(yytext)); return OperatorUpEq;
						}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 308 "lexer.l"
{
							yylval.node_type = new Node("OperatorVertEq", string(yytext)); return OperatorVertEq;
						}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 312 "lexer.l"
{
							yylval.node_type = new Node("KeywordBoolean", string(yytext)); return KeywordBoolean;
						}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 316 "lexer.l"
{
							yylval.node_type = new Node("KeywordByte", string(yytext)); return KeywordByte;
						}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 320 "lexer.l"
{
							yylval.node_type = new Node("KeywordShort", string(yytext)); return KeywordShort;
						}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 324 "lexer.l"
{
							yylval.node_type = new Node("KeywordInt", string(yytext)); return KeywordInt;
						}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 328 "lexer.l"
{
							yylval.node_type = new Node("KeywordLong", string(yytext)); return KeywordLong;
						}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 331 "lexer.l"
{
							yylval.node_type = new Node("KeywordChar", string(yytext)); return KeywordChar;
						}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 335 "lexer.l"
{
							yylval.node_type = new Node("KeywordFloat", string(yytext)); return KeywordFloat;
						}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 339 "lexer.l"
{
							yylval.node_type = new Node("KeywordDouble", string(yytext)); return KeywordDouble;
						}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 342 "lexer.l"
{
							yylval.node_type = new Node("KeywordClass", string(yytext)); return KeywordClass;
						}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 345 "lexer.l"
{
							yylval.node_type = new Node("KeywordVoid", string(yytext)); return KeywordVoid;
						}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 349 "lexer.l"
{
							yylval.node_type = new Node("KeywordIf", string(yytext)); return KeywordIf;
						}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 352 "lexer.l"
{
							yylval.node_type = new Node("KeywordElse", string(yytext)); return KeywordElse;
						}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 355 "lexer.l"
{
							yylval.node_type = new Node("KeywordSwitch", string(yytext)); return KeywordSwitch;
						}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 358 "lexer.l"
{
							yylval.node_type = new Node("KeywordCase", string(yytext)); return KeywordCase;
						}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 361 "lexer.l"
{
							yylval.node_type = new Node("KeywordDefault", string(yytext)); return KeywordDefault;
						}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 364 "lexer.l"
{
							yylval.node_type = new Node("KeywordWhile", string(yytext)); return KeywordWhile;
						}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 367 "lexer.l"
{
							yylval.node_type = new Node("KeywordBreak", string(yytext)); return KeywordBreak;
						}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 370 "lexer.l"
{
							yylval.node_type = new Node("KeywordContinue", string(yytext)); return KeywordContinue;
						}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 373 "lexer.l"
{
							yylval.node_type = new Node("KeywordReturn", string(yytext)); return KeywordReturn;
						}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 376 "lexer.l"
{
							yylval.node_type = new Node("KeywordThis", string(yytext)); return KeywordThis;
						}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 379 "lexer.l"
{
							yylval.node_type = new Node("KeywordNew", string(yytext)); return KeywordNew;
						}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 382 "lexer.l"
{
							yylval.node_type = new Node("KeywordInstanceof", string(yytext)); return KeywordInstanceof;
						}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 385 "lexer.l"
{
							yylval.node_type = new Node("KeywordFor", string(yytext)); return KeywordFor;
						}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 388 "lexer.l"
{
							yylval.node_type = new Node("KeywordDo", string(yytext)); return KeywordDo;
						}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 392 "lexer.l"
{
							yylval.node_type = new Node("KeywordSuper", string(yytext)); return KeywordSuper;
						}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 395 "lexer.l"
{
							yylval.node_type = new Node("KeywordThrow", string(yytext)); return KeywordThrow;
						}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 398 "lexer.l"
{
							yylval.node_type = new Node("KeywordTry", string(yytext)); return KeywordTry;
						}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 401 "lexer.l"
{
							yylval.node_type = new Node("KeywordCatch", string(yytext)); return KeywordCatch;
						}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 404 "lexer.l"
{
							yylval.node_type = new Node("KeywordPackage", string(yytext)); return KeywordPackage;
						}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 407 "lexer.l"
{
							yylval.node_type = new Node("KeywordPublic", string(yytext)); return KeywordPublic;
						}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 410 "lexer.l"
{
							yylval.node_type = new Node("KeywordStatic", string(yytext)); return KeywordStatic;
						}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 413 "lexer.l"
{
							yylval.node_type = new Node("KeywordAbstract", string(yytext)); return KeywordAbstract;
						}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 416 "lexer.l"
{
							yylval.node_type = new Node("KeywordFinal", string(yytext)); return KeywordFinal;
						}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 419 "lexer.l"
{
							yylval.node_type = new Node("KeywordFinally", string(yytext)); return KeywordFinally;
						}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 422 "lexer.l"
{
							yylval.node_type = new Node("KeywordImplements", string(yytext)); return KeywordImplements;
						}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 425 "lexer.l"
{
							yylval.node_type = new Node("KeywordInterface", string(yytext)); return KeywordInterface ;
						}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 428 "lexer.l"
{
							yylval.node_type = new Node("KeywordPrivate", string(yytext)); return KeywordPrivate;
						}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 431 "lexer.l"
{
							yylval.node_type = new Node("KeywordNative", string(yytext)); return KeywordNative;
						}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 434 "lexer.l"
{
							yylval.node_type = new Node("KeywordProtected", string(yytext)); return KeywordProtected;
						}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 437 "lexer.l"
{
							yylval.node_type = new Node("KeywordSynchronized", string(yytext)); return KeywordSynchronized;

						}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 441 "lexer.l"
{
							yylval.node_type = new Node("KeywordTransient", string(yytext)); return KeywordTransient;
						}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 444 "lexer.l"
{
							yylval.node_type = new Node("KeywordVolatile", string(yytext)); return KeywordVolatile;
						}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 447 "lexer.l"
{
							yylval.node_type = new Node(" KeywordThrows", string(yytext)); return KeywordThrows;
						}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 450 "lexer.l"
{
							yylval.node_type = new Node(" KeywordExtends", string(yytext)); return KeywordExtends;
						}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 453 "lexer.l"
{
							yylval.node_type = new Node(" KeywordImport", string(yytext)); return KeywordImport;
						}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 463 "lexer.l"
{yylval.node_type = new Node("Keyword", string(yytext)); return Keyword;  }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 465 "lexer.l"
{
							yylval.node_type = new Node("BooleanLiteral", string(yytext));
							return BooleanLiteral;
						}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 470 "lexer.l"
{
							yylval.node_type = new Node("NullLiteral", string(yytext));
							return NullLiteral;
						}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 475 "lexer.l"
{ BEGIN(IN_STRING); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 477 "lexer.l"
{  yylval.node_type = new Node("CharacterLiteral", string(yytext)); return CharacterLiteral ; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 478 "lexer.l"
{ cout << "error character single quote in line no - "<< yylineno <<"\n" ; exit(0);}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 481 "lexer.l"
{ yylval.node_type = new Node("FloatingLiteral", string(yytext)); return FloatingLiteral ;   }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 483 "lexer.l"
{ yylval.node_type = new Node("Identifier", string(yytext)); return Identifier ;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 486 "lexer.l"
{ yylval.node_type = new Node("IntegerLiteral", string(yytext)); return IntegerLiteral ;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 488 "lexer.l"
{ cout << yytext <<"  invalid, error in line no- " << yylineno <<"\n" ; exit(0);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 490 "lexer.l"
{ yylval.node_type = new Node("IntegerLiteral", string(yytext)); return IntegerLiteral ;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 492 "lexer.l"
{ cout << yytext <<"  invalid, error in line no- " << yylineno <<"\n" ; exit(0);}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 494 "lexer.l"
{ yylval.node_type = new Node("IntegerLiteral", string(yytext)); return IntegerLiteral ;} 
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 496 "lexer.l"
{ cout << yytext <<"  invalid, error in line no- " << yylineno <<"\n"; exit(0);}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 497 "lexer.l"
{
             if(*yytext=='0' && yyleng > 1 && yytext[yyleng-1] != 'L' && yytext[yyleng-1] != 'l')
             {   
                 yymore();
                 cout << "invalid, decimal error in line no- " << yylineno<<"\n" ;    exit(0);  
             }
             else { yylval.node_type = new Node("IntegerLiteral", string(yytext)); return IntegerLiteral ;}
                                
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 508 "lexer.l"
{  cout << yytext <<"    invalid character error in lineno- " << yylineno <<"\n"; exit(0) ;}
	YY_BREAK


case 113:
YY_RULE_SETUP
#line 514 "lexer.l"
{
							BEGIN(INITIAL);
							;
						}
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 518 "lexer.l"
{ cout <<"error: Unterminated comment in line no  " << yylineno << "\n"; exit(0); return 0; }
	YY_BREAK
case 114:
/* rule 114 can match eol */
YY_RULE_SETUP
#line 519 "lexer.l"
{yylineno++; yymore();}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 520 "lexer.l"
yymore();
	YY_BREAK


case 116:
YY_RULE_SETUP
#line 523 "lexer.l"
{
							BEGIN(INITIAL);	
							string s  = string(yytext);
							s.erase(s.end()-1, s.end());
							yylval.node_type = new Node("StringLiteral", s); return StringLiteral ;
                                                        
						}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 530 "lexer.l"
{yymore();}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 531 "lexer.l"
{
							BEGIN(INITIAL); 
							 cout<< "error of escape_sequence in string literal in line no "<< yylineno<<"\n" ; exit(0);
						}
	YY_BREAK
case YY_STATE_EOF(IN_STRING):
#line 535 "lexer.l"
{ cout << " error of EOF in string literal in line no "<< yylineno<<"\n" ; exit(0);}
	YY_BREAK
case 119:
/* rule 119 can match eol */
YY_RULE_SETUP
#line 536 "lexer.l"
{
							yylineno++; 
							yytext[yyleng-1] = '\0'; 
							BEGIN(INITIAL); 
							 cout << " error of line_terminator in string literal in line no "<< yylineno <<"\n"; exit(0);
						}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 542 "lexer.l"
yymore();
	YY_BREAK

case 121:
YY_RULE_SETUP
#line 545 "lexer.l"
ECHO;
	YY_BREAK
#line 1936 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 417 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 417 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 416);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 545 "lexer.l"


int yywrap(void)
{
	return  1;
}




